apiVersion: v1
kind: ServiceAccount
metadata:
  name: ai-secops-agent
  namespace: ai-enclave
  labels:
    azure.workload.identity/use: "true"
    azawslab.phase: O6
    azawslab.o6/agent: "true"
  annotations:
    azure.workload.identity/client-id: "REPLACE_WITH_ID_AI_SECOPS_AGENT_CLIENT_ID"
